version: "3.8"
#networks:
#  proxy_net:
#    external: true
services:
  cli3-server:
    build: .
    ports:
      - "5050:5050"
    container_name: cli3-server
#    networks:
#      - proxy_net
  cli3-client:
    build: ./client
    ports:
      - "7088:80"
    container_name: cli3-client
#    volumes:
#      - /Users/avglek/WebstormProjects/cli/new/cli3pro-server/client/nginx.conf:/etc/nginx/nginx.conf
