version: "3.8"
networks:
  cli3-net:
#    external: true
services:
  cli3-server:
    build: .
#    ports:
#       - "5000:5000"
    container_name: cli3-server
    networks:
      - cli3-net
    volumes:
 #     - /Users/avglek/WebstormProjects/cli/cli3/config
      - /home/glek/cli3/config:/usr/src/app/config
  cli3-client:
    build: ./client
    ports:
      - "7058:80"
    container_name: cli3-client
    networks:
      - cli3-net
#    volumes:
#      - /client/nginx.conf:/etc/nginx/nginx.conf
