module.exports.type = {
  DATA_TYPE: 'DB_TYPE_DATE',
  DATE: 'DATE',
  CLOB: 'DB_TYPE_NCLOB',
  REF_CURSOR: 'DB_TYPE_CURSOR',
  OBJECT: 'DB_TYPE_OBJECT',
  CHAR: 'DB_TYPE_CHAR',
  NUMBER: 'DB_TYPE_NUMBER',
  VARCHAR2: 'DB_TYPE_VARCHAR',
  TABLE: 'DB_TYPE_CURSOR',
};
module.exports.dir = {
  OUT: 'BIND_OUT',
  IN: 'BIND_IN',
};
